/*
 * Public API of @bored-games/protocol: NOSTR events for the Bored Games protocol (docs/PROTOCOL.md).
 * Signing and verification use @noble/curves `schnorr` directly, not nostr-tools (D026).
 */
export { ProtocolError } from './errors.ts';
export {
  type AttestSpec,
  type Audit,
  attestTemplate,
  type CardSharesSpec,
  cardSharesTemplate,
  type DeviceNoteSpec,
  deviceNoteTemplate,
  type EndAttestSpec,
  type EndedBy,
  type EndKind,
  type EndResult,
  endAttestTemplate,
  logHash,
  type MoveContent,
  type MoveSpec,
  moveTemplate,
  type Outcome,
  type Parsed,
  type ParsedAttest,
  type ParsedCardShares,
  type ParsedDeviceNote,
  type ParsedEndAttest,
  type ParsedMove,
  type ParsedResign,
  type ParsedRollShares,
  type ParsedSecret,
  type ParsedShares,
  type ParsedStatsAttest,
  type ParsedTimeout,
  type PosShare,
  parseAttest,
  parseAttestV2,
  parseDeviceNote,
  parseMove,
  parseResign,
  parseSecret,
  parseShares,
  parseSharesV2,
  parseTimeout,
  type ResignSpec,
  type RollSharesSpec,
  resignTemplate,
  rollSharesTemplate,
  type SecretSpec,
  type SharesSpec,
  secretTemplate,
  sharesTemplate,
  type TimeoutSpec,
  timeoutTemplate,
} from './game.ts';
export { DEADLINES, DEFAULT_DEADLINE, KIND, MAX_EVENT_BYTES, PROTO, PROTOS, type Proto } from './kinds.ts';
export {
  isRelayUrl,
  type JoinSpec,
  joinTemplate,
  makeJoinPok,
  type ParsedJoin,
  type ParsedRoot,
  type ParsedTable,
  parseJoin,
  parseRoot,
  parseTable,
  type RootSeat,
  type RootSpec,
  rootTemplate,
  rulesHash,
  sessionMessage,
  signSession,
  type TableSpec,
  type TableStatus,
  tableAddress,
  tableTemplate,
  validateRoot,
  validateTable,
  verifyJoin,
} from './lobby.ts';
export {
  type EventTemplate,
  eventBytes,
  eventId,
  finalizeEvent,
  getPublicKey,
  type Hex,
  isHex64,
  type NostrEvent,
  sha256Hex,
  verifyEvent,
} from './nostr.ts';
export { many, named, one, requireProto } from './tags.ts';
