/*
 * Public API of @bored-games/protocol: NOSTR events for the Bored Games protocol (docs/PROTOCOL.md).
 * Signing and verification use @noble/curves `schnorr` directly, not nostr-tools (D026).
 */
export {
  encodeKeyBackup,
  isKeyBackupEvent,
  type KeyBackup,
  keyBackupD,
  keyBackupTemplate,
  parseKeyBackup,
} from './backup.ts';
export { ProtocolError } from './errors.ts';
export {
  type AttestSpec,
  type Audit,
  attestTemplate,
  type EndedBy,
  logHash,
  type MoveContent,
  type MoveSpec,
  moveTemplate,
  type Outcome,
  type Parsed,
  type ParsedAttest,
  type ParsedMove,
  type ParsedResign,
  type ParsedSealed,
  type ParsedSecret,
  type ParsedShares,
  type ParsedTimeout,
  type PosSealed,
  type PosShare,
  parseAttest,
  parseMove,
  parseResign,
  parseSealed,
  parseSecret,
  parseShares,
  parseTimeout,
  type ResignSpec,
  resignTemplate,
  type SealedSpec,
  type SecretSpec,
  type SharesSpec,
  sealedTemplate,
  secretTemplate,
  sharesTemplate,
  type TimeoutSpec,
  timeoutTemplate,
} from './game.ts';
export { DEADLINES, DEFAULT_DEADLINE, KIND, MAX_EVENT_BYTES, PROTO } from './kinds.ts';
export {
  isRelayUrl,
  type JoinSpec,
  joinTemplate,
  makeJoinPok,
  type ParsedJoin,
  type ParsedRoot,
  type ParsedTable,
  parseJoin,
  parseRoot,
  parseTable,
  type RootSeat,
  type RootSpec,
  rootTemplate,
  rulesHash,
  sessionMessage,
  signSession,
  type TableSpec,
  type TableStatus,
  tableAddress,
  tableTemplate,
  validateRoot,
  verifyJoin,
} from './lobby.ts';
export { getConversationKey, isNip44Payload, nip44Decrypt, nip44Encrypt } from './nip44.ts';
export {
  type EventTemplate,
  eventBytes,
  eventId,
  finalizeEvent,
  getPublicKey,
  type Hex,
  isHex64,
  type NostrEvent,
  sha256Hex,
  verifyEvent,
} from './nostr.ts';
export { many, named, one, requireProto } from './tags.ts';
